name: Update movie data

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: "0 2,8 * * *"
    # - cron: "0 4,10 * * *"
    - cron: "0 6,12 * * *"
    - cron: "0 7,13 * * *"
  workflow_dispatch:

jobs:
  process:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    env:
      USER: ${{ github.repository_owner }}
      REPO_NAME: ${{ secrets.REPO_CINE }}
      SRC_NAME: source

    steps:
      - uses: actions/checkout@v6

      - name: Checkout src repo
        uses: actions/checkout@v6
        with:
          repository: ${{ env.USER }}/${{ env.REPO_NAME }}
          token: ${{ secrets.GH_TOKEN_ACCESS }}
          path: ${{ env.SRC_NAME }}
          fetch-depth: 1
          ref: ${{ github.ref }}

      - name: Set up Python 3
        uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - name: Cache pip
        uses: actions/cache@v5
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          pushd ${SRC_NAME} &&
          pip install -U -r requirements.txt >/dev/null 2>&1
          popd

      - name: Run script maoyan
        if: github.event.schedule == '0 2,8 * * *'
        run: |
          pushd ${SRC_NAME} &&
          bash scripts/run-top.sh maoyan &&
          popd

      # - name: Run script imdb
      #   if: github.event.schedule == '0 4,10 * * *'
      #   run: |
      #     pushd ${SRC_NAME} &&
      #     bash scripts/run-top.sh imdb &&
      #     popd

      - name: Run script tmdb
        if: github.event.schedule == '0 6,12 * * *'
        run: |
          pushd ${SRC_NAME} && 
          bash scripts/run-top.sh tmdb &&
          popd

      - name: Run script allocine
        if: github.event.schedule == '0 7,13 * * *'
        run: |
          pushd ${SRC_NAME} && 
          bash scripts/run-top.sh allocine &&
          popd

      - name: Git auto commit
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit_message: Automated update
          # commit_options: '--no-verify --signoff'
          push_options: "--force"
          # file_pattern: "*.json"
