name: Update test

on:
  workflow_dispatch:

jobs:
  process:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    env:
      USER: ${{ github.repository_owner }}
      REPO_NAME: ${{ secrets.REPO_CINE }}
      SRC_NAME: source

    steps:
      - uses: actions/checkout@v6

      - name: Checkout src repo
        uses: actions/checkout@v6
        with:
          repository: ${{ env.USER }}/${{ env.REPO_NAME }}
          token: ${{ secrets.GH_TOKEN_ACCESS }}
          path: ${{ env.SRC_NAME }}
          fetch-depth: 1
          ref: ${{ github.ref }}

      - name: Set up Python 3
        uses: actions/setup-python@v6
        with:
          python-version: 3.x

      # - name: Install uv
      #   uses: astral-sh/setup-uv@v7
      # - name: Install the project
      #   run: uv sync --locked --all-extras --dev
      # - name: Set up Python
      #   run: uv python install

      # - name: Cache pip
      #   uses: actions/cache@v5
      #   with:
      #     path: ~/.cache/pip
      #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          pushd ${SRC_NAME} &&
          pip install -U -r requirements.txt >/dev/null 2>&1
          popd

      - name: Run scripts
        run: |
          pushd ${SRC_NAME} || exit 0
          bash scripts/run-top.sh maoyan
          bash scripts/run-top.sh imdb
          bash scripts/run-top.sh tmdb
          bash scripts/run-top.sh allocine
          popd

      - name: Git auto commit
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit_message: Automated update
          # commit_options: '--no-verify --signoff'
          push_options: "--force"
          file_pattern: "*.json"
